# Generated by Django 4.0.1 on 2022-01-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='topic',
        ),
    ]
