# Generated by Django 4.0.1 on 2022-01-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(choices=[('Web Frameworks', 'Web Frameworks'), ('URL Mapping', 'URL Mapping'), ('Setting up Django', 'Setting up Django')], max_length=500),
        ),
    ]
